### ISSUE TITLE
blockfrost-client 0.8.0.0 doesn't build with GHC 9.6.3

### ISSUE THREAD

**Issue by jonathangenlambda** [blockfrost/blockfrost-haskell#47]
Building blockfrost-client 0.8.0.0 seems to be failing when building with GHC 9.6.3 with the following error:
```
Building library for blockfrost-client-0.8.0.0..
[ 1 of 16] Compiling Blockfrost.Client.Types ( src/Blockfrost/Client/Types.hs, dist/build/Blockfrost/Client/Types.o, dist/build/Blockfrost/Client/Types.dyn_o )
[ 2 of 16] Compiling Blockfrost.Client.NutLink ( src/Blockfrost/Client/NutLink.hs, dist/build/Blockfrost/Client/NutLink.o, dist/build/Blockfrost/Client/NutLink.dyn_o )
[ 3 of 16] Compiling Blockfrost.Client.IPFS ( src/Blockfrost/Client/IPFS.hs, dist/build/Blockfrost/Client/IPFS.o, dist/build/Blockfrost/Client/IPFS.dyn_o )

src/Blockfrost/Client/IPFS.hs:31:14: error: [GHC-88464]
    Variable not in scope: liftIO :: IO Bool -> m Bool
    Suggested fix: Perhaps use 'liftA2' (imported from Prelude)
   |
31 |   hasFile <- liftIO $ System.Directory.doesFileExist fp
   |              ^^^^^^

src/Blockfrost/Client/IPFS.hs:34:7: error: [GHC-88464]
    Variable not in scope: liftIO :: IO () -> m a0
    Suggested fix: Perhaps use 'liftA2' (imported from Prelude)
   |
34 |       liftIO $ putStrLn $ "Uploading: " ++ fp
   |       ^^^^^^
```
The problem stems from the fact that `Control.Monad.Except` doesn't reexport `Control.Monad.Trans` anymore which in turn reexported `Control.Monad.IO.Class`.

Please repair or adjust dependencies, as https://hackage.haskell.org/package/blockfrost-client reports `base (>=4.7 && <5)`

**Comment by sorki** [comment]
Thanks, fixed and released as `blockfrost-client-0.8.0.1`.
